### ISSUE TITLE
create navbar

### ISSUE THREAD

**Issue by BrooksMWest** [nss-evening-cohort-27/pos-terminal-pizza-hill-gang#14]
# TO SCOPE THIS TICKET:

- [ ] they should see a navbar with a brand
- [ ] A logout button in the navbar
- [ ] A link to view all orders in the navbar// FUNCTIONALITY NOT NEEDED YET
- [ ] A link to Create an Order in the navbar// FUNCTIONALITY NOT NEEDED YET

## 🧑 Story

We need a navbar that is accessible from every page that our user access (persistent) with clickable links to access create an order form, and a view all orders as well as a logout button to exit the application. 

 

## 🔨 Acceptance Criteria

- Navbar contains all elements: they should see a navbar with a brand, logout button in the navbar, link to view all orders in, link to Create an Order.
- is persistent on each page

 

## 📚 Resources

- [FIGMADOC1][(WWWDOTEXAMPLEDOTCOM](https://www.figma.com/design/4y3EZddALuBR3ouSEM57Np/MVP?node-id=0-1&t=1Ab6D4Is6eZY1z07-0))

 

![Image](https://github.com/nss-evening-cohort-27/pos-terminal-pizza-hill-gang/assets/134945403/f468a867-0a24-4d4e-971e-d553c8a6efea)

**Comment by TrevorMustoe** [comment]
![Image](https://github.com/nss-evening-cohort-27/pos-terminal-pizza-hill-gang/assets/113145432/cb4bea4c-8586-4d4b-9076-6ae5ce2b197c)
